jpa:
  properties:
    hibernate:
      format_sql: true
      check_nullability: true

logging:
  level:
    org:
      hibernate:
        sql: debug # 쿼리 파라미터 출력


# 운영환경에서는 p6spy 사용 X
decorator:
  datasource:
    p6spy:
      enable-logging: false