# 운영환경
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/algoNote;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update # 운영 장비에서는 절대 crate, create-drop, update 사용하면 안된다. (개발 초기 단계는 create 또는 update)
    properties:
      hibernate:
        default_batch_fetch_size: 100
#    open-in-view: false
  profiles:
    include: oauth, log

server:
  servlet:
    encoding:
      charset : UTF-8
      force : true
